platform :ios, '11.0'
inhibit_all_warnings!

def shared_pods 
  use_frameworks!

  pod 'RxSwift', '>= 4.2.0'
  pod 'RxCocoa', '>= 4.0.0'
  pod 'RxFlow', '>= 2.0.0'
  pod 'Reusable', '4.0.5'
  pod 'SwiftLint', '0.27.0'
  pod 'Alamofire', '4.7.3'
  pod 'XCGLogger', '7.0.0'
  pod 'SwiftGen', '~> 6.0'
  pod 'lottie-ios'
  pod 'KeychainAccess', '3.1.1'
  pod 'SnapKit', '4.2.0'
  pod 'DeployGateSDK'
  
end

target 'dev' do
  shared_pods
end

target 'prod' do
  shared_pods
end

target 'stg' do
  shared_pods
end
